# Generated by Django 4.1 on 2022-11-02 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ejemplo', '0002_empresa'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mascota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_mascota', models.CharField(max_length=100)),
                ('animal', models.CharField(max_length=300)),
                ('telefono_dueño', models.IntegerField()),
            ],
        ),
    ]
